import type { Metadata } from "next";
import { rubik } from './fonts';
import { Header } from '../components';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={`${rubik.variable}`}> 
    
      <body className="">
        <Header/>
        {children}
      </body> 
    </html>
  );
}
